### ISSUE TITLE
Deployment Key chicken/egg

### ISSUE THREAD

**Issue by cbowlesut** [puppetlabs/control-repo#13]
Quick question about the Deployment key.  The README instructions have you create the deploy key manually on the Puppet Server, then add the deployment key to the git Repo.

However, there is also code to do the same, which never runs if you follow the default instructions.  Is there another way to solve the bootstrap problem of getting the server connected to the control repo, or is the deployment key code a future enhancement?

side-note:  this repo is awesome, thanks a bunch!
Chris

**Comment by npwalker** [comment]
@cbowlesut The only way I know how to avoid the need for a deploy key is to allow your control repo to be cloned without authentication.

If you have an api token for your git management system you could script out creating the key and adding it to your repo so you could then run r10k to get your code onto the master.  

Glad you find the repo useful!

**Comment by cbowlesut** [comment]
@npwalker   Thanks!

FYI, I was able to side-step the issue by using a service account to hold the code_manager SSH key.  I ended up commenting out the deployment key logic in profile::git_webhook, since the key was the same and attempting to add the deploy key caused an error.
