### ISSUE TITLE
Alternative Git Repository Location?

### ISSUE THREAD

**Issue by krische** [puppetlabs/control-repo#24]
Is it possible to setup an alternative git repository location and project name? `puppet/control-repo` isn't really desirable in my environment and it seems like it is hard-coded to that.

**Comment by pjmorr** [comment]
I changed mine.. Don't know why you wouldn't be able to, you just have to remember the locations if you do fetch updates.

**Comment by krische** [comment]
So would I just edit the `site/profile/manifests/git_webhook/code_manager.pp` file and replace `project_name => 'puppet/control-repo',` with my custom path?

**Comment by natemccurdy** [comment]
@krische Yeah, there's really no issue with changing the name of this to anything you want. You'll just need to make sure you use the new name in:

* https://github.com/puppetlabs/control-repo/blob/production/site/profile/manifests/git_webhook/code_manager.pp#L135
* https://github.com/puppetlabs/control-repo/blob/production/site/profile/manifests/git_webhook/code_manager.pp#L144
* The r10k_remote parameter on your Puppet Masters: https://docs.puppetlabs.com/pe/latest/code_mgr_config.html#qpuppetmasterr10kremote or https://docs.puppetlabs.com/pe/latest/code_mgr_config.html#configure-after-pe-installation

**Comment by npwalker** [comment]
@krische I'd recommend using the PR here that uses the pe_code_manager_module that I just broke out and has a parameter for changing the name of the control-repo. 

https://github.com/puppetlabs/control-repo/pull/22

https://github.com/npwalker/pe_code_manager_webhook/blob/master/manifests/code_manager.pp#L12
