### ISSUE TITLE
Add example for hiera.yaml

### ISSUE THREAD

**Issue by slauger** [puppetlabs/control-repo#31]
Please add an example for an environment specific hiera.yaml. 

Currently the hieradata folder in this example doesen't work with PE because the default hiera.yaml doesen't include a definition for e.g. "node/%{trusted.certname}".

**Comment by npwalker** [comment]
@slauger which version of PE are you using?  I believe `node/%{trusted.certname}` is in the default hierarchy starting in PE2015.2

**Comment by npwalker** [comment]
@slauger I'm going to close this out for now.  Since there hasn't been any further activity.

**Comment by jessereynolds** [comment]
Also it's worth noting that the environment specific hiera.yaml file in v4 format is experimental and will be changing, so probably not a good thing to be building into this repo at the moment.
