### ISSUE TITLE
Make repo a GitHub template repository

### ISSUE THREAD

**Issue by lfarnell** [puppetlabs/control-repo#77]
## Use Case
Configure the repository to be a GitHub Template repository. 

## Describe the Solution You Would Like
Based on the instructions [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) configure the repository to be a GitHub template repository for easier use for GitHub users and/or new Puppet users.

## Describe Alternatives You've Considered
The current [method](https://github.com/puppetlabs/control-repo#copy-this-repo-into-your-own-git-server) of use would/could apply.

## Additional Context
NA

**Comment by npwalker** [comment]
Done.  Thanks for the suggestion!
